# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Pay-As-You-Go (b1dacf81-f466-4dfe-a1f6-fe5c6a365f1e)'
    subscriptionId: 'b1dacf81-f466-4dfe-a1f6-fe5c6a365f1e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AD'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/onlyforlab/VMAD/main/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/onlyforlab/VMAD/main/parameters.json'
    deploymentMode: 'Validation'